spring:
  profiles:
    active: production
---

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3309/Demo1"
    username: "paulo"
    password: "password"
